name: ProShop CI/CD Pipeline

on:
  push:
    branches: [ "main", "master" ] # Jab bhi in branches par code push hoga, pipeline chalegi

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # Hum hamesha 'latest' tag use karenge taqe server automatically naya code utha le
          tags: ${{ secrets.DOCKER_USERNAME }}/proshop-app:latest 

  deploy-to-aws:
    name: Deploy to Private App Server
    needs: build-and-push # Yeh job pehli job complete hone ke baad chalegi
    runs-on: ubuntu-latest
    steps:
      - name: SSH into Private Server and Update
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.APP_SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          # Yeh do lines jadoo hain! GitHub Actions khud Bastion ke zariye Jump lagayega
          proxy_host: ${{ secrets.BASTION_IP }}
          proxy_username: ubuntu
          proxy_key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            sudo docker compose pull proshop-app
            sudo docker compose up -d